---
- name: Set sap_hosts_group based on the input
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Set sap_hosts_group variable dynamically based on location
      ansible.builtin.set_fact:
        sap_hosts_group: >-
          {{ 'sap' if location == 'both' else
             hostvars[item].cluster_name if location == hostvars[item].city
             else 'sap' }}
      with_items: "{{ groups['sap'] }}"
      when: location is defined

- name: Execute a script on the AIX jump host
  hosts: aix_jumphost
  gather_facts: false
  tasks:
    - name: Show the initiators to be added
      ansible.builtin.debug:
        msg: "Adding initiators: {{ initiators }}"
#    - name: Execute the get WWN command
#      ansible.builtin.raw: "{{ get_wwn_cmd }}"
#      register: wwns
#      when: initiators is not defined
#
#    - name: Show initiators (must be a comma separeted list)
#      ansible.builtin.debug:
#        msg: "{{ wwns.stdout_lines | join(',') }}"
#      when: initiators is not defined

    - name: Set initiators variable
      ansible.builtin.set_fact:
        stored_wwns: "{{ initiators }}"

- name: Add initiators to the igroup fcp_{{ aix_host }}_01
  hosts: "{{ hostvars['localhost']['sap_hosts_group'] }}"
  serial: 1
  gather_facts: false
  tasks:
    - name: Show the initiators to be added
      ansible.builtin.debug:
        msg: "Adding initiators: {{ hostvars['GDC00620']['stored_wwns'] }}"

    - name: Include role igroup initiator
      ansible.builtin.include_role:
        name: sgs.ontap.igroup
        tasks_from: initiator.yml
      vars:
        state: present
        vserver: "{{ vserver_sap_fc }}"
        initiator_group: "fcp_{{ aix_host }}_01"
        names: "{{ hostvars['localhost']['stored_wwns'] }}"
